In [23]:

import pandas as pd



labels  = pd.read_csv("../data/outputs/2026-03-27_19-52-38/provider_level.csv")

In [24]:
labels

,billing_provider_npi,months_observed,first_month,last_month,span_months,missing_months_within_span,fraction_months_observed,mean_gap_months,max_gap_months,paid_t_mean,...,hcpcs_paid_hhi_minus_claim_hhi_t_mean_abs_monthlyized_change,hcpcs_paid_hhi_minus_claim_hhi_t_median_abs_monthlyized_change,hcpcs_paid_hhi_minus_claim_hhi_t_max_abs_monthlyized_change,hcpcs_paid_hhi_minus_claim_hhi_t_spike_ratio_max_to_median,hcpcs_paid_hhi_minus_claim_hhi_t_spike_ratio_max_to_mean,hcpcs_paid_hhi_minus_claim_hhi_t_largest_monthlyized_increase,hcpcs_paid_hhi_minus_claim_hhi_t_largest_monthlyized_decrease,hcpcs_paid_hhi_minus_claim_hhi_t_max_abs_deviation_from_median,insufficient_history_flag,label
0,1003001264,21,2020-11,2023-06,32,11,0.656250,1.550000,4.0,3386.391905,...,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0,0
1,1003002932,30,2021-02,2024-11,46,16,0.652174,1.551724,5.0,1330.095333,...,0.002364,0.000000,0.028896,NaN,NaN,0.028896,0.028896,0.028896,0,0
2,1003004698,57,2020-01,2024-11,59,2,0.966102,1.035714,2.0,13909.849825,...,0.041984,0.029479,0.146563,NaN,NaN,0.139223,0.146563,0.146563,0,0
3,1003011172,54,2020-01,2024-11,59,5,0.915254,1.094340,5.0,3211.600370,...,0.047792,0.031466,0.191342,NaN,NaN,0.191342,0.184075,0.170616,0,0
4,1003012246,58,2020-01,2024-10,58,0,1.000000,1.000000,1.0,1821.219138,...,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8810,1992962385,14,2020-10,2022-02,17,3,0.823529,1.230769,4.0,3673.988571,...,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0,0
8811,1992977649,15,2020-01,2024-09,57,42,0.263158,4.000000,20.0,537.573333,...,0.266203,0.115940,1.500000,NaN,NaN,1.500000,0.541351,1.000000,0,0
8812,1992989578,23,2020-01,2023-08,44,21,0.522727,1.954545,14.0,1015.697826,...,0.038025,0.000000,0.594492,NaN,NaN,0.594492,0.050700,0.710463,0,0
8813,1992990915,6,2021-09,2022-05,9,3,0.666667,1.600000,2.0,4440.000000,...,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0,0
8814,1992997928,57,2020-01,2024-12,60,3,0.950000,1.053571,2.0,18047.160526,...,0.064195,0.045571,0.235783,NaN,NaN,0.235783,0.192551,0.276451,0,0

In [22]:
(labels['label'] != 0).sum()

np.int64(17)

In [ ]:
df = pd.read_csv("../data/datasets/revocations.csv")

In [18]:
df

,ENRLMT_ID,NPI,FIRST_NAME,MDL_NAME,LAST_NAME,ORG_NAME,MULTIPLE_NPI_FLAG,STATE_CD,PROVIDER_TYPE_DESC,REVOCATION_RSN,REVOCATION_EFCTV_DT,REENROLLMENT_BAR_EXPRTN_DT
0,I20031105000097,1.801839e+09,MARGARET,L,KEITH,NaN,N,FL,PRACTITIONER - INTERNAL MEDICINE,424.535(A)(2) Provider Or Supplier Conduct (Ex...,05/20/2025,07/31/2030
1,I20031106000430,1.568430e+09,JUAN,Y,KURDI,NaN,N,TX,PRACTITIONER - CARDIOVASCULAR DISEASE (CARDIOL...,424.535(A)(13) Prescribing Authority,09/28/2023,09/27/2028
2,I20031112000226,1.669421e+09,JEREMY,T,ADAMS,NaN,N,CA,PRACTITIONER - CERTIFIED REGISTERED NURSE ANES...,424.535(A)(9) Failure To Report;424.535(A)(12)...,02/17/2023,03/18/2028
3,I20031112000231,1.174565e+09,MARIO,M,SANTILLANES,NaN,N,CA,PRACTITIONER - INTERNAL MEDICINE,424.535(A)(12) Other Program Termination (Medi...,04/01/2021,03/31/2026
4,I20031112000491,1.043202e+09,MARK,NaN,FETTMAN,NaN,N,CA,PRACTITIONER - PSYCHIATRY,424.535(A)(3) Felonies,05/01/2025,05/01/2035
...,...,...,...,...,...,...,...,...,...,...,...,...
7460,O20250725003820,1.871332e+09,NaN,NaN,NaN,"STORY AVE 24, LLC",N,NY,DME SUPPLIER - PHARMACY,424.535(A)(1) Noncompliance (Dme Standards Not...,10/28/2025,12/03/2027
7461,O20250804000746,1.629951e+09,NaN,NaN,NaN,ASIS REHAB & MEDICAL CENTER LLC,N,FL,PART B SUPPLIER - CLINIC/GROUP PRACTICE,424.535(A)(5) On-Site Review;424.535(A)(9) Fai...,10/08/2025,12/13/2028
7462,O20250805001388,1.649975e+09,NaN,NaN,NaN,AS MEDICAL EQUIPMENTS CORP,N,FL,PART B SUPPLIER - CLINIC/GROUP PRACTICE,424.535(A)(8)(I) Abuse Of Billing Privileges,11/23/2025,11/22/2035
7463,O20250902001631,1.255216e+09,NaN,NaN,NaN,LLA PLUS SERVICES INC,N,FL,PART B SUPPLIER - CLINIC/GROUP PRACTICE,424.535(A)(4) False Or Misleading Information,10/17/2025,10/16/2035
7464,O20250903003539,1.972395e+09,NaN,NaN,NaN,SUDEEP CLINIC CENTER CORP,N,FL,PART B SUPPLIER - CLINIC/GROUP PRACTICE,424.535(A)(4) False Or Misleading Information,11/14/2025,11/13/2035

In [15]:
df.dtypes

ENRLMT_ID                         str
NPI                           float64
FIRST_NAME                        str
MDL_NAME                          str
LAST_NAME                         str
ORG_NAME                          str
MULTIPLE_NPI_FLAG                 str
STATE_CD                          str
PROVIDER_TYPE_DESC                str
REVOCATION_RSN                    str
REVOCATION_EFCTV_DT               str
REENROLLMENT_BAR_EXPRTN_DT        str
dtype: object

In [11]:
df['REVOCATION_RSN'].nunique()

118

In [16]:
for r in df['REVOCATION_RSN'].unique():
    print(r)

424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(13) Prescribing Authority
424.535(A)(9) Failure To Report;424.535(A)(12) Other Program Termination (Medicaid)
424.535(A)(12) Other Program Termination (Medicaid)
424.535(A)(3) Felonies
424.535(A)(1) Noncompliance (Not Professionally Licensed);424.535(A)(9) Failure To Report
424.535(A)(9) Failure To Report;424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(9) Failure To Report;424.535(A)(3) Felonies
424.535(A)(3) Felonies;424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(9) Failure To Report;424.535(A)(3) Felonies;424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(8)(Ii) Abuse Of Billing Privileges: Pattern Or Practice
424.535(A)(10) Failure To Document
424.535(A)(4) False Or Misleading Information;424.535(A)(9) Failure To Report
424.535(A)(4) False Or Misleading Information;424.535(A)(9) Failure To Report;424.535(A)(3) Felonies
424.535(A)(9) Failure To Report;424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(3) Felonies;424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(9) Failure To Report;424.535(A)(3) Felonies;424.535(A)(22) Patient Harm
424.535(A)(9) Failure To Report;424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(3) Felonies
424.535(A)(19) Affiliation That Poses An Undue Risk
424.535(A)(9) Failure To Report;424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(3) Felonies
424.535(A)(9) Failure To Report;424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(2) Provider Or Supplier Conduct (Other)
424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(3) Felonies;424.535(A)(2) Provider Or Supplier Conduct (Other)
424.535(A)(9) Failure To Report;424.535(A)(3) Felonies;424.535(A)(12) Other Program Termination (Other Federal Health Care Program)
424.535(A)(14) Improper Prescribing Practices
424.535(A)(4) False Or Misleading Information;424.535(A)(9) Failure To Report;424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(3) Felonies
424.535(A)(1) Noncompliance (Provider/Supplier Type Requirements Not Met);424.535(A)(9) Failure To Report
424.535(A)(9) Failure To Report;424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(22) Patient Harm
424.535(A)(1) Noncompliance (Not Professionally Licensed)
424.535(A)(9) Failure To Report;424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(3) Felonies;424.535(A)(13) Prescribing Authority
424.535(A)(10) Failure To Document;424.535(A)(3) Felonies
424.535(A)(9) Failure To Report;424.535(A)(8)(Ii) Abuse Of Billing Privileges: Pattern Or Practice
424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(3) Felonies;424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(9) Failure To Report;424.535(A)(12) Other Program Termination (Other Federal Health Care Program)
424.535(A)(4) False Or Misleading Information;424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(3) Felonies;424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(4) False Or Misleading Information;424.535(A)(9) Failure To Report;424.535(A)(3) Felonies;424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(17) Debt Referred To Treasury
424.535(A)(1) Noncompliance (Not Professionally Licensed);424.535(A)(4) False Or Misleading Information;424.535(A)(9) Failure To Report
424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(8)(Ii) Abuse Of Billing Privileges: Pattern Or Practice
424.535(A)(9) Failure To Report;424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(8)(Ii) Abuse Of Billing Privileges: Pattern Or Practice
424.535(A)(9) Failure To Report;424.535(A)(22) Patient Harm
424.535(A)(22) Patient Harm
424.535(A)(3) Felonies;424.535(A)(2) Provider Or Supplier Conduct (Other)
424.535(A)(3) Felonies;424.535(A)(13) Prescribing Authority
424.535(A)(9) Failure To Report;424.535(A)(3) Felonies;424.535(A)(2) Provider Or Supplier Conduct (Other)
424.535(A)(3) Felonies;424.535(A)(12) Other Program Termination (Other Federal Health Care Program);424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(1) Noncompliance (Business Location Not Properly Licensed);424.535(A)(9) Failure To Report
424.535(A)(9) Failure To Report;424.535(A)(2) Provider Or Supplier Conduct (Other)
424.535(A)(9) Failure To Report;424.535(A)(10) Failure To Document;424.535(A)(3) Felonies
424.535(A)(4) False Or Misleading Information;424.535(A)(3) Felonies
424.535(A)(9) Failure To Report;424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(2) Provider Or Supplier Conduct (Exclusion);424.535(A)(22) Patient Harm
424.535(A)(12) Other Program Termination (Other Federal Health Care Program)
424.535(A)(4) False Or Misleading Information;424.535(A)(8)(Ii) Abuse Of Billing Privileges: Pattern Or Practice
424.535(A)(9) Failure To Report;424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(3) Felonies;424.535(A)(2) Provider Or Supplier Conduct (Other)
424.535(A)(9) Failure To Report;424.535(A)(2) Provider Or Supplier Conduct (Exclusion);424.535(A)(22) Patient Harm
424.535(A)(9) Failure To Report;424.535(A)(1) Noncompliance (Enrollment Requirements)
424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(8)(I) Abuse Of Billing Privileges;424.535(A)(9) Failure To Report
424.535(A)(2) Provider Or Supplier Conduct (Other)
424.535(A)(2) Provider Or Supplier Conduct (Exclusion);424.535(A)(22) Patient Harm
424.535(A)(1) Noncompliance (Not Professionally Licensed);424.535(A)(9) Failure To Report;424.535(A)(3) Felonies;424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(9) Failure To Report;424.535(A)(8)(Ii) Abuse Of Billing Privileges: Pattern Or Practice;424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(9) Failure To Report;424.535(A)(13) Prescribing Authority
424.535(A)(1) Noncompliance (Provider/Supplier Type Requirements Not Met);424.535(A)(3) Felonies
424.535(A)(1) Noncompliance (Provider/Supplier Type Requirements Not Met)
424.535(A)(4) False Or Misleading Information;424.535(A)(9) Failure To Report;424.535(A)(1) Noncompliance (Enrollment Requirements)
424.535(A)(4) False Or Misleading Information;424.535(A)(3) Felonies;424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(9) Failure To Report;424.535(A)(3) Felonies;424.535(A)(2) Provider Or Supplier Conduct (Exclusion);424.535(A)(13) Prescribing Authority
424.535(A)(9) Failure To Report;424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(3) Felonies;424.535(A)(2) Provider Or Supplier Conduct (Exclusion);424.535(A)(22) Patient Harm
424.535(A)(9) Failure To Report;424.535(A)(3) Felonies;424.535(A)(13) Prescribing Authority
424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(22) Patient Harm
424.535(A)(9) Failure To Report;424.535(A)(10) Failure To Document
424.535(A)(4) False Or Misleading Information
424.535(A)(1) Noncompliance (Enrollment Requirements)
424.535(A)(5) On-Site Review;424.535(A)(9) Failure To Report
424.535(A)(5) On-Site Review;424.535(A)(9) Failure To Report;424.535(A)(17) Debt Referred To Treasury
424.535(A)(8)(I) Abuse Of Billing Privileges
424.535(A)(5) On-Site Review
424.535(A)(5) On-Site Review;424.535(A)(9) Failure To Report;424.535(A)(3) Felonies
424.535(A)(5) On-Site Review;424.535(A)(17) Debt Referred To Treasury
424.535(A)(5) On-Site Review;424.535(A)(3) Felonies
424.535(A)(1) Noncompliance (Dme Standards Not Met)
424.535(A)(9) Failure To Report
424.535(A)(1) Noncompliance (Business Location Not Properly Licensed);424.535(A)(1) Noncompliance (Dme Standards Not Met)
424.535(A)(1) Noncompliance (Business Location Not Properly Licensed)
424.535(A)(5) On-Site Review;424.535(A)(8)(Ii) Abuse Of Billing Privileges: Pattern Or Practice
424.535(A)(10) Failure To Document;424.535(A)(8)(Ii) Abuse Of Billing Privileges: Pattern Or Practice
424.535(A)(5) On-Site Review;424.535(A)(9) Failure To Report;424.535(A)(19) Affiliation That Poses An Undue Risk
424.535(A)(4) False Or Misleading Information;424.535(A)(9) Failure To Report;424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(5) On-Site Review;424.535(A)(9) Failure To Report;424.535(A)(3) Felonies;424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(5) On-Site Review;424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(3) Felonies
424.535(A)(8)(Ii) Abuse Of Billing Privileges: Pattern Or Practice;424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(1) Noncompliance (Idtf Standards Not Met)
424.535(A)(8)(Ii) Abuse Of Billing Privileges: Pattern Or Practice;424.535(A)(19) Affiliation That Poses An Undue Risk
424.535(A)(9) Failure To Report;424.535(A)(3) Felonies;424.535(A)(12) Other Program Termination (Other Federal Health Care Program);424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(8)(I) Abuse Of Billing Privileges;424.535(A)(10) Failure To Document
424.535(A)(4) False Or Misleading Information;424.535(A)(5) On-Site Review
424.535(A)(5) On-Site Review;424.535(A)(9) Failure To Report;424.535(A)(8)(Ii) Abuse Of Billing Privileges: Pattern Or Practice
424.535(A)(5) On-Site Review;424.535(A)(8)(I) Abuse Of Billing Privileges;424.535(A)(9) Failure To Report
424.535(A)(4) False Or Misleading Information;424.535(A)(9) Failure To Report;424.535(A)(3) Felonies;424.535(A)(23) Violation Of Provider And Supplier Standards
424.535(A)(4) False Or Misleading Information;424.535(A)(5) On-Site Review;424.535(A)(9) Failure To Report
424.535(A)(5) On-Site Review;424.535(A)(9) Failure To Report;424.535(A)(10) Failure To Document;424.535(A)(8)(Ii) Abuse Of Billing Privileges: Pattern Or Practice
424.535(A)(23) Violation Of Provider And Supplier Standards
424.535(A)(5) On-Site Review;424.535(A)(19) Affiliation That Poses An Undue Risk
424.535(A)(4) False Or Misleading Information;424.535(A)(2) Provider Or Supplier Conduct (Exclusion)
424.535(A)(1) Noncompliance (Dme Standards Not Met);424.535(A)(1) Noncompliance (Enrollment Requirements)
424.535(A)(9) Failure To Report;424.535(A)(3) Felonies;424.535(A)(19) Affiliation That Poses An Undue Risk
424.535(A)(4) False Or Misleading Information;424.535(A)(12) Other Program Termination (Medicaid);424.535(A)(3) Felonies
424.535(A)(18) Revoked Under Different Name, Numerical Identifier Or Business Identity
424.535(A)(1) Noncompliance (Dme Standards Not Met);424.535(A)(23) Violation Of Provider And Supplier Standards
424.535(A)(4) False Or Misleading Information;424.535(A)(8)(I) Abuse Of Billing Privileges
424.535(A)(1) Noncompliance (Dme Standards Not Met);424.535(A)(8)(I) Abuse Of Billing Privileges
424.535(A)(5) On-Site Review;424.535(A)(9) Failure To Report;424.535(A)(23) Violation Of Provider And Supplier Standards
424.535(A)(4) False Or Misleading Information;424.535(A)(8)(I) Abuse Of Billing Privileges;424.535(A)(3) Felonies
424.535(A)(8)(Ii) Abuse Of Billing Privileges: Pattern Or Practice;424.535(A)(23) Violation Of Provider And Supplier Standards
424.535(A)(5) On-Site Review;424.535(A)(1) Noncompliance (Dme Standards Not Met);424.535(A)(9) Failure To Report
424.535(A)(9) Failure To Report;424.535(A)(19) Affiliation That Poses An Undue Risk
424.535(A)(5) On-Site Review;424.535(A)(1) Noncompliance (Dme Standards Not Met);424.535(A)(9) Failure To Report;424.535(A)(8)(Ii) Abuse Of Billing Privileges: Pattern Or Practice
424.535(A)(4) False Or Misleading Information;424.535(A)(5) On-Site Review;424.535(A)(8)(I) Abuse Of Billing Privileges;424.535(A)(9) Failure To Report

In [ ]:
overlap = set(df['NPI'].dropna().astype(int)) & set(labels[labels['NPI'] != 0]['NPI'])
print(f"Overlap: {len(overlap)} NPIs")

Overlap: 1271 NPIs

In [17]:
billing_npis = set(df[df['REVOCATION_RSN'].str.contains('Billing', case=False, na=False)]['NPI'].dropna().astype(int))
overlap = billing_npis & set(labels[labels['NPI'] != 0]['NPI'])
print(f"Overlap: {len(overlap)} NPIs")

Overlap: 3 NPIs

In [ ]:
(all_cohorts["anomalies"] == 0).sum()

0      False
1      False
2      False
3      False
4      False
       ...
104     True
105     True
106     True
107     True
108     True
Name: anomalies, Length: 109, dtype: bool

In [4]:
all_cohorts[all_cohorts["anomalies"] == 0]

     cohort     cohort_label  total_providers  anomalies  anomaly_rate
70      102  UT_organization             2479          0           0.0
71      106  VI_organization               98          0           0.0
72      105    VI_individual               26          0           0.0
73      104  VA_organization             9744          0           0.0
74      110  WA_organization             5712          0           0.0
75       98  TN_organization             6658          0           0.0
76      114  WV_organization             2977          0           0.0
77      101    UT_individual             2409          0           0.0
78      112  WI_organization             5242          0           0.0
79       95    SD_individual              137          0           0.0
80       96  SD_organization             1526          0           0.0
81      108  VT_organization              936          0           0.0
82       62  MS_organization             4259          0           0.0
83       86  OR_organization             4152          0           0.0
84       84  OK_organization             5052          0           0.0
85        4  AL_organization             5319          0           0.0
86       14  CO_organization             9619          0           0.0
87       16  CT_organization             4931          0           0.0
88       17    DC_individual              568          0           0.0
89       18  DC_organization              783          0           0.0
90       24  FM_organization                1          0           0.0
91       26  GA_organization             1420          0           0.0
92       27    GU_individual               39          0           0.0
93       28  GU_organization               69          0           0.0
94       30  HI_organization             1876          0           0.0
95       32  IA_organization             4354          0           0.0
96       33    ID_individual              680          0           0.0
97       34  ID_organization             2643          0           0.0
98       36  IL_organization             4769          0           0.0
99       48  MD_organization             9259          0           0.0
100      50  ME_organization             2072          0           0.0
101      64  MT_organization             1910          0           0.0
102      66  NC_organization            13690          0           0.0
103      68  ND_organization             1058          0           0.0
104      70  NE_organization             2593          0           0.0
105      71    NH_individual              627          0           0.0
106      72  NH_organization             1420          0           0.0
107      76  NM_organization             3166          0           0.0
108     116  WY_organization              916          0           0.0

In [19]:

import numpy as np

PROVIDER_LEVEL_CSV = "../data/outputs/multirun/2026-03-27_14-31-33/1/provider_level.csv"
MISS_THRESHOLD = 0.05
CONST_THRESHOLD = 0.01
CORR_THRESHOLD  = 0.9

META_COLS = {
    "billing_provider_npi", "label", "excldate", "revocation_rsn",
    "cohort_label", "insufficient_history_flag",
    "months_observed", "first_month", "last_month",
    "span_months", "missing_months_within_span",
    "fraction_months_observed", "mean_gap_months", "max_gap_months",
}

pl = pd.read_csv(PROVIDER_LEVEL_CSV, low_memory=False)
feat_cols = [c for c in pl.columns if c not in META_COLS]
X = pl[feat_cols].copy()

# ── 1. Drop high-missingness features ─────────────────────────────────────────
miss_frac = X.isna().mean()
drop_miss = miss_frac[miss_frac > MISS_THRESHOLD].index.tolist()
X = X.drop(columns=drop_miss)
print(f"Dropped {len(drop_miss)} high-missingness features (>{MISS_THRESHOLD:.0%} NaN)  → {X.shape[1]} remain")

# ── 2. Drop near-constant features ────────────────────────────────────────────
std = X.std(skipna=True)
drop_const = std[std < CONST_THRESHOLD].index.tolist()
X = X.drop(columns=drop_const)
print(f"Dropped {len(drop_const)} near-constant features (std < {CONST_THRESHOLD})     → {X.shape[1]} remain")

# ── 3. Correlation prune at 0.9 ───────────────────────────────────────────────
corr = X.corr().abs()
upper = corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))
drop_corr = [col for col in upper.columns if any(upper[col] > CORR_THRESHOLD)]
X = X.drop(columns=drop_corr)
print(f"Dropped {len(drop_corr)} correlated features (r > {CORR_THRESHOLD})            → {X.shape[1]} remain")

print(f"\nFinal feature set: {X.shape[1]} features across {X.shape[0]} providers")
X.head()

Dropped 60 high-missingness features (>5% NaN)  → 552 remain
Dropped 4 near-constant features (std < 0.01)     → 548 remain
Dropped 326 correlated features (r > 0.9)            → 222 remain

Final feature set: 222 features across 2924 providers

,paid_t_mean,paid_t_min,paid_t_slope,paid_t_cv,paid_t_spike_ratio_max_to_median,paid_t_spike_ratio_max_to_mean,paid_t_max_monthlyized_pct_growth,paid_t_largest_monthlyized_pct_drop,paid_t_changepoint_count,paid_t_largest_relative_level_shift,...,hcpcs_paid_hhi_minus_claim_hhi_t_iqr,hcpcs_paid_hhi_minus_claim_hhi_t_slope,hcpcs_paid_hhi_minus_claim_hhi_t_mad,hcpcs_paid_hhi_minus_claim_hhi_t_mean_abs_monthlyized_change,hcpcs_paid_hhi_minus_claim_hhi_t_median_abs_monthlyized_change,hcpcs_paid_hhi_minus_claim_hhi_t_max_abs_monthlyized_change,hcpcs_paid_hhi_minus_claim_hhi_t_max_abs_deviation_from_median,hcpcs_paid_hhi_minus_claim_hhi_t_changepoint_count,hcpcs_paid_hhi_minus_claim_hhi_t_fraction_flagged_months,hcpcs_paid_hhi_minus_claim_hhi_t_max_consecutive_flagged_obs
0,361836.193500,108427.37,-5052.177557,0.308831,1.554132,1.556772,0.501539,0.531888,15.0,0.421731,...,0.044864,-0.001040,0.021628,0.011863,0.007748,0.047942,0.070092,0.0,0.421053,6
1,542.427273,319.80,-2.427455,0.455150,2.487070,1.850995,1.540048,0.632870,2.0,1.009158,...,0.000000,-0.000020,0.000000,0.000149,0.000000,0.001116,0.001116,0.0,0.000000,0
2,2297.005455,989.04,-321.967818,0.565553,2.661844,2.106525,0.496114,0.576112,2.0,0.525824,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0
3,6607.844655,767.14,-3.682451,0.493103,1.923828,1.985483,6.647911,0.781910,16.0,5.494131,...,0.070125,0.001292,0.029634,0.061530,0.046955,0.313058,0.240914,0.0,0.418182,4
4,1498.689636,298.92,-2.154224,0.351649,1.710640,1.783692,1.200000,0.579044,14.0,0.705762,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0